I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 208, in script
    Kaz "Hey [playerName] look! It's Kasumi!"
KeyError: u'playerName'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 208, in script
    Kaz "Hey [playerName] look! It's Kasumi!"
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 690, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\exports.py", line 1316, in say
    who(what, *args, **kwargs)
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1118, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1107, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\substitutions.py", line 244, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'playerName'

Windows-8-6.2.9200
Ren'Py 7.2.0.424
Project Lintahlo 1.0
Fri Mar 15 19:39:39 2019
